spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:h2:mem:paydb # 테스트용 메모리 DB (실제 운영시 MySQL 등으로 변경)
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update # 테이블 자동 생성
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7

jwt:
  secret:
    key: ${JWT_SECRET}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY:your_access_key}
      secret-key: ${AWS_SECRET_KEY:your_secret_key}
    region:
      static: ${AWS_REGION:ap-northeast-2}
    stack:
      auto: false
    s3:
      bucket: ${AWS_S3_BUCKET:your_bucket_name}


naver-search:
  client-id: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}